### ISSUE TITLE
Can't compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by christophetd** [NateBrune/fmem#2]
FYI, I'm unable to compile fmem on Ubuntu 16.04 with kernel 4.13 : 

```
$ make
rm -f *.o *.ko *.mod.c Module.symvers Module.markers modules.order \.*.o.cmd \.*.ko.cmd \.*.o.d
rm -rf \.tmp_versions
make -C /lib/modules/`uname -r`/build SUBDIRS=`pwd` modules
make[1]: Entering directory '/usr/src/linux-headers-4.13.0-36-generic'
  CC [M]  /home/christophetd/fmem-master/lkm.o
/home/christophetd/fmem-master/lkm.c: In function ‘memory_lseek’:
/home/christophetd/fmem-master/lkm.c:289:42: error: ‘struct inode’ has no member named ‘i_mutex’
  mutex_lock(&file->f_path.dentry->d_inode->i_mutex);
                                          ^
/home/christophetd/fmem-master/lkm.c:310:44: error: ‘struct inode’ has no member named ‘i_mutex’
  mutex_unlock(&file->f_path.dentry->d_inode->i_mutex);
                                            ^
scripts/Makefile.build:308: recipe for target '/home/christophetd/fmem-master/lkm.o' failed
make[2]: *** [/home/christophetd/fmem-master/lkm.o] Error 1
Makefile:1550: recipe for target '_module_/home/christophetd/fmem-master' failed
make[1]: *** [_module_/home/christophetd/fmem-master] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-36-generic'
Makefile:12: recipe for target 'fmem' failed
make: *** [fmem] Error 2
```

**Comment by Phikimon** [comment]
lol, there already was a pull request #1 fixing your issue at the time you opened it

**Comment by NateBrune** [comment]
@Phikimon @christophetd sorry for the delay on this issue, but I think we can close it now.
